/**:
  ros__parameters:
    publish_rate: 1.0
    frame_id: camera_color_optical_frame
    camera_name: d457
    loop: false
    voxel_leaf_size: 0.05
    sor_mean_k: 20.0
    sor_std_mul: 0.5
    statistics_enabled: true
    use_sor: true
    use_euclidean_cluster: true
    sacline_distance_threshold: 0.1
    evaluation_timeout_seconds: 65
    groundtruth_eval_enabled: false
    groundtruth_images_dir: ""
    groundtruth_camera_info_file: config/d457_color.yaml
    groundtruth_tag_size_m: 0.05
    cluster_mode: 2
    color_image_topic: /camera/color/image_raw
    depth_image_topic: /camera/depth/image_rect_raw
    color_camera_info_topic: /camera/color/camera_info
    depth_camera_info_topic: /camera/depth/camera_info
    mask_topic: /yolo/mask
    input_mode: driver
    debug_flags: ["debug_cloud"]
    save_visualization: true
    save_every_n: 1
